// flow-typed signature: ae225d42a1d949a868757acaeba82a32
// flow-typed version: <<STUB>>/object-sizeof_v1.2.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-sizeof'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-sizeof' {
  declare module.exports: (arg: any) => number;
}
